        # Tachyon Webmail configuration.
        rewrite ^/tachyon$ /tachyon/ redirect;
        rewrite ^/tachyon/$ /tachyon/index.php;
        location /tachyon/ {
                index index.php;
                alias /usr/local/share/tachyonmail/;
        }
        location ~ /tachyon/.*\.php {
                # note: ~ has precedence over a regular location block
                include fastcgi_params;
                fastcgi_split_path_info ^/tachyon(/.*)()$;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME /usr/local/share/tachyonmail/$fastcgi_script_name;
                fastcgi_param SCRIPT_NAME $fastcgi_script_name;
                fastcgi_pass php-fpm-tachyonmail;

                # Outgoing mail also goes through this endpoint, so increase the maximum
                # file upload limit to match the corresponding Postfix limit.
                client_max_body_size 128M;
        }

