               # By default not blocked
                set $block_test 1;

                # block the continents
                if ($allowed_continent = no) {
                        set $block_test 0;
                }

                # in addition, block the countries
                if ($denied_country = no) {
                        set $block_test 0;
                }

                # allow some countries
                if ($allowed_country = yes) {
                        set $block_test 1;
                }

                # if 0, then blocked
                if ($block_test = 0) {
                        access_log /var/log/nginx/geoipblock.log geoipblock;
                        return 444;
                }
# Uncomment to test allowed countries
#                if ($block_test = 1) {
#                        access_log /var/log/nginx/geoipblock.log geoippassed;
#                }
